name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the latest Docker image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Stop and remove old container
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Run new container
        run: |
          docker run -d --name my-app -p 80:80 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
